# coding: utf-8

"""
    Doi Server API

    A Digital Object Identifier (DOI) is an alphanumeric string assigned to uniquely identify an object. It is tied to a metadata description of the object as well as to a digital location, such as a URL, where all the details about the object are accessible. This documentation provides an API to query the DOI-server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: jean-christophe.malapert@cnes.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.data_cite_metadata_store__mds_api_api import DataCiteMetadataStoreMDSAPIApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDataCiteMetadataStoreMDSAPIApi(unittest.TestCase):
    """DataCiteMetadataStoreMDSAPIApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.data_cite_metadata_store__mds_api_api.DataCiteMetadataStoreMDSAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_doi_project(self):
        """Test case for cancel_doi_project

        """
        pass

    def test_get_all_doi_metadata(self):
        """Test case for get_all_doi_metadata

        """
        pass

    def test_get_doi_media(self):
        """Test case for get_doi_media

        """
        pass

    def test_get_landing_page_url(self):
        """Test case for get_landing_page_url

        """
        pass

    def test_post_doi_metadata(self):
        """Test case for post_doi_metadata

        """
        pass

    def test_post_landing_page(self):
        """Test case for post_landing_page

        """
        pass

    def test_post_media(self):
        """Test case for post_media

        """
        pass


if __name__ == '__main__':
    unittest.main()
