# coding: utf-8

"""
    Doi Server API

    Doi Server API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest
import test_util;
from test_util import TestUtil
import swagger_client
from swagger_client.api.mds_api import MdsApi  # noqa: E501
from swagger_client.rest import ApiException
#from Tools.scripts.objgraph import ignore


class TestMdsApi(unittest.TestCase):
    """MdsApi unit test stubs"""

     

    def setUp(self):
        # Configure API key authorization: APIKeyHeader
        configuration = swagger_client.Configuration()
        configuration.host = TestUtil.httpsbasePath()
        configuration.api_key['Authorization'] = 'eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIke3Byb2plY3QuYXJ0aWZhY3RJZH0iLCJpYXQiOjE1NDk0NjE0MzgsInN1YiI6InRlc3QiLCJwcm9qZWN0SUQiOjgyODYwNiwicHJvamVjdE5hbWUiOiJDRk9TQVQiLCJleHAiOjQ3MDUxMzUwMzh9.XDAtZIXbXNlbq4PE4RLNEnJC8mGtU7oFgjq7BWoIAQM'
        # Uncomment below to setup prefix (e.g. Bearer) for API key, if needed
        configuration.api_key_prefix['Authorization'] = 'Bearer'
        self.api = swagger_client.api.mds_api.MdsApi(swagger_client.ApiClient(configuration))  # noqa: E501

    def tearDown(self):
        pass

    
    def test_cancel_doi_project(self):
        
        api_response = self.api.cancel_doi_project(TestUtil.doi_name())
        assert api_response == "OK"
        
    
    def test_post_doi_metada(self):
        metadata = TestUtil.doi_metadata()
        api_response = self.api.post_doi_metada(TestUtil.doi_metadata());
        api_response == "OK (" + TestUtil.doi_name() + ")"
        pass
    
    """def test_post_media(self):
        api_response = self.api.post_media(TestUtil.doi_name(), TestUtil.doi_media());
        assert(api_response == "OK");
        pass"""
    
    def test_post_doi(self):
        
        api_response = self.api.post_doi(TestUtil.doi_landingPageUrl(), TestUtil.doi_name());
        assert(api_response == "OK"); 
        pass
    
    
    def test_get_landing_page_url(self):
         api_response = self.api.get_landing_page_url(TestUtil.doi_name());
         assert(api_response == TestUtil.doi_landingPageUrl());
         pass     

    
    """def test_get_doi_media(self):
        api_response = self.api.get_doi_media(TestUtil.doi_name());
        assert (api_response == TestUtil.doi_media());
        pass"""
    
    
    def test_get_all_dois(self):
        api_response = self.api.get_all_dois();
        assert(api_response == "10.24400/329360/F7Q52MNK");
        pass
    
    
    def test_get_all_doi_metadata(self):
        api_response = self.api.get_all_doi_metadata(TestUtil.doi_name());
        assert(api_response != "");
        pass

if __name__ == '__main__':
    unittest.main()
