# coding: utf-8

# flake8: noqa
"""
    Doi Server API

    A Digital Object Identifier (DOI) is an alphanumeric string assigned to uniquely identify an object. It is tied to a metadata description of the object as well as to a digital location, such as a URL, where all the details about the object are accessible. This documentation provides an API to query the DOI-server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: jean-christophe.malapert@cnes.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
