# coding: utf-8

"""
    Doi Server API

    Doi Server API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest
import test_util;
from test_util import TestUtil
import swagger_client
from swagger_client.api.citation_api import CitationApi  # noqa: E501
from swagger_client.rest import ApiException
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration


class TestCitationApi(unittest.TestCase):
    """CitationApi unit test stubs"""

    def setUp(self):
        conf = Configuration()
        conf.host = TestUtil.httpbasePath()
        self.api = swagger_client.api.citation_api.CitationApi(ApiClient(conf))  # noqa: E501

    def tearDown(self):
        pass

    def test_get_citation(self):
        response = self.api.get_citation("10.23641/asha.5233939", TestUtil.doi_style(), TestUtil.doi_lang());
        citation = "Elina Niemitalo-Haapola, Sini Haapala, Teija Kujala, Antti Raappana, Tiia Kujala و Eira Jansson-Verkasalo, \"Developmental and noise-induced changes (Niemitalo-Haapola et al., 2017)\".\n"
        assert (response == citation)
        pass

    def test_get_citations_language(self):
        response = self.api.get_citations_language()
        assert (response == TestUtil.doi_languages())
        pass

    def test_get_citations_style(self):
        response = self.api.get_citations_style()
        assert(len(response) != 0)
        pass

if __name__ == '__main__':
    unittest.main()
